{
 "title": "Github",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Stars",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_stars",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page views",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_repo count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_views",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "$tag_repo uniques",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_views",
     "select": [
      [
       { "params": [ "uniques" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page views per path",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "$tag_path count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_paths",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "$tag_path uniques",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo::tag" ], "type": "tag" },
      { "params": [ "path::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_paths",
     "select": [
      [
       { "params": [ "uniques" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clones",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "alias": "$tag_repo count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_clones",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "$tag_repo uniques",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_clones",
     "select": [
      [
       { "params": [ "uniques" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Referrals",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "$tag_repo $tag_referrer count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo::tag" ], "type": "tag" },
      { "params": [ "referrer::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_referrals",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "$tag_repo $tag_referrer uniques",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo::tag" ], "type": "tag" },
      { "params": [ "referrer::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_referrals",
     "select": [
      [
       { "params": [ "uniques" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Forks",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "alias": "$tag_repo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_forks",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_repo $tag_workflow",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo::tag" ], "type": "tag" },
      { "params": [ "workflow::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "github_stats_actions",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}